# -------------------------
#
# Cwago.
#
# cwago/Cargo.toml
# (C) 2023 CwagoCommunity.
#
# cwagoワークスペースの設定です。
# =========================

[workspace]

members = [
    "cwago_utility",
    "cwago_memory",
    "cwago_comp",
    "cwago_ecs",
]